
-- Seeding Recommendation Pool Data based on src/lib/meal-recommendation.ts

INSERT INTO public.recommendation_pool (id, title, description, category, tags, metadata, image_url, ingredients, process_steps, tips, difficulty, time_required, servings, calories)
VALUES
(
    'pork-belly',
    '솥뚜껑 삼겹살',
    '캠핑의 국룰! 김치와 함께 구워먹는 삼겹살 파티',
    'cooking',
    ARRAY['#고기', '#저녁', '#술안주'],
    '{"season": ["spring", "summer", "autumn", "winter"]}',
    'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["삼겹살 600g", "묵은지 1포기", "마늘", "쌈장", "상추", "버섯"]',
    '["솥뚜껑을 달군 후 비계로 기름칠을 합니다.", "삼겹살을 올리고 아래쪽에 김치를 둡니다.", "노릇하게 구워지면 먹기 좋게 자릅니다.", "마지막에 김치와 밥을 볶아 드세요!"]',
    '솥뚜껑 중앙에 기름이 모이니 김치를 거기 두세요.',
    1,
    30,
    '2-3',
    800
),
(
    'oden-soup',
    '꼬치 어묵탕',
    '쌀쌀한 날씨에 딱! 따끈한 국물과 쫄깃한 어묵',
    'cooking',
    ARRAY['#국물', '#따뜻한', '#겨울철'],
    '{"season": ["autumn", "winter"], "weather": ["rainy", "snowy", "cloudy"]}',
    'https://images.unsplash.com/photo-1610970881699-44a5587cabec?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["꼬치어묵 10개", "무 1/4개", "대파 1대", "청양고추 2개", "멸치육수 팩"]',
    '["물 1.5L에 육수팩과 무를 넣고 끓입니다.", "육수가 우러나면 어묵 꼬치를 넣습니다.", "대파와 고추를 넣고 한소끔 더 끓입니다.", "간장으로 간을 맞춥니다."]',
    '무를 얇게 썰면 빨리 익고 국물이 시원해집니다.',
    1,
    20,
    '3-4',
    400
),
(
    'grilled-skewers',
    '모듬 꼬치구이',
    '맥주 안주로 최고! 하나씩 빼먹는 재미가 있어요',
    'cooking',
    ARRAY['#꼬치', '#안주', '#간식'],
    '{"season": ["spring", "summer", "autumn"]}',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["닭다리살 300g", "대파 2대", "파프리카 1개", "소떡소떡 세트", "데리야끼 소스"]',
    '["재료를 한입 크기로 썹니다.", "꼬치에 재료를 번갈아 끼웁니다.", "숯불이나 팬에 노릇하게 굽습니다.", "소스를 발라가며 한번 더 굽습니다."]',
    '꼬치를 물에 불려두면 탈지 않습니다.',
    2,
    40,
    '2',
    500
),
(
    'kimchi-stew',
    '돼지고기 김치찌개',
    '한국인의 소울푸드, 해장으로도 그만이죠',
    'cooking',
    ARRAY['#찌개', '#한식', '#얼큰한'],
    '{"season": ["spring", "summer", "autumn", "winter"]}',
    'https://images.unsplash.com/photo-1583562479633-87a3cbdd5112?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["돼지고기(목살) 300g", "김치 1/4포기", "두부 1모", "대파", "다진마늘"]',
    '["돼지고기랑 김치를 먼저 볶습니다.", "물을 붓고 푹 끓입니다.", "두부와 대파를 넣고 마무리합니다."]',
    '쌀뜨물을 사용하면 국물이 더 진해집니다.',
    2,
    30,
    '3',
    600
),
(
    'gambas',
    '감바스 알 아히요',
    '와인 한 잔과 함께 즐기는 스페인 요리',
    'cooking',
    ARRAY['#양식', '#분위기', '#와인'],
    '{"season": ["spring", "summer", "autumn", "winter"]}',
    'https://images.unsplash.com/photo-1565557623262-b51c2513a641?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["칵테일 새우 15마리", "통마늘 10개", "페페론치노", "올리브유", "바게트"]',
    '["팬에 올리브유를 넉넉히 두릅니다.", "편마늘을 넣고 약불에 튀기듯 볶습니다.", "새우와 페페론치노를 넣고 익힙니다.", "바게트를 곁들여 냅니다."]',
    '기름이 끓을 때 새우 물기를 제거하고 넣어야 튀지 않아요.',
    1,
    15,
    '2',
    700
),
(
    'ramen',
    '해물 라면',
    '신선한 해물을 넣어 끓인 최고의 야식',
    'cooking',
    ARRAY['#면요리', '#야식', '#간단'],
    '{"season": ["spring", "summer", "autumn", "winter"]}',
    'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["라면 2봉지", "새우 2마리", "오징어무", "대파", "고춧가루"]',
    '["물을 끓일 때 해물을 먼저 넣습니다.", "물이 끓으면 스프와 면을 넣습니다.", "마지막에 대파와 고춧가루를 뿌립니다."]',
    '스프를 먼저 넣으면 끓는점이 높아져 면이 꼬들해집니다.',
    1,
    10,
    '2',
    500
),
(
    'dakgalbi',
    '춘천 닭갈비',
    '매콤달콤한 양념에 볶음밥까지 완벽한 코스',
    'cooking',
    ARRAY['#닭고기', '#볶음밥', '#메인요리'],
    '{"season": ["spring", "summer", "autumn", "winter"]}',
    'https://images.unsplash.com/photo-1628268878950-80d859b4344d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["닭갈비 밀키트", "양배추", "고구마", "떡사리", "우동사리"]',
    '["팬을 달구고 닭고기를 껍질부터 익힙니다.", "채소를 넣고 같이 볶습니다.", "마지막에 사리를 추가합니다.", "남은 양념에 밥을 볶습니다."]',
    '고구마가 익으면 다 익은 것입니다.',
    2,
    30,
    '3-4',
    700
),
(
    'shabu',
    '밀푀유 나베',
    '보기에도 예쁘고 맛도 좋은 따뜻한 전골 요리',
    'cooking',
    ARRAY['#전골', '#손님초대', '#비주얼'],
    '{"season": ["autumn", "winter"]}',
    'https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["소고기(샤브용)", "배추", "깻잎", "표고버섯", "육수"]',
    '["배추-깻잎-고기 순으로 겹겹이 쌓습니다.", "냄비 높이에 맞춰 자릅니다.", "냄비에 빈틈없이 채워 담습니다.", "육수를 붓고 끓입니다."]',
    '칠리소스와 폰즈소스를 곁들이면 더 맛있습니다.',
    2,
    40,
    '3',
    400
),
(
    'corn-cheese',
    '콘치즈',
    '아이들도 좋아하는 달달하고 고소한 간식',
    'cooking',
    ARRAY['#간식', '#아이들', '#치즈'],
    '{"season": ["spring", "summer", "autumn", "winter"]}',
    'https://images.unsplash.com/photo-1551024506-0bccd828d307?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    '["옥수수 통조림 1캔", "모짜렐라 치즈", "마요네즈", "설탕", "버터"]',
    '["옥수수 물기를 뺍니다.", "마요네즈와 설탕을 섞습니다.", "팬에 버터를 녹이고 옥수수를 볶습니다.", "치즈를 올리고 뚜껑을 덮어 녹입니다."]',
    '파슬리 가루를 뿌리면 더 먹음직스럽습니다.',
    1,
    10,
    '2',
    300
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    metadata = EXCLUDED.metadata,
    image_url = EXCLUDED.image_url,
    ingredients = EXCLUDED.ingredients,
    process_steps = EXCLUDED.process_steps,
    tips = EXCLUDED.tips,
    difficulty = EXCLUDED.difficulty,
    time_required = EXCLUDED.time_required,
    servings = EXCLUDED.servings,
    calories = EXCLUDED.calories;
