import { Site } from '@/types/reservation';

export const SITES: Site[] = [
    {
        id: 'site-1',
        name: '철수네',
        type: 'AUTO',
        description: '숲속 가장 깊은 곳, 조용한 휴식을 위한 프라이빗 사이트입니다.',
        price: 40000,
        basePrice: 40000,
        maxOccupancy: 4,
        imageUrl: '/images/tent_view_hero.png',
        features: ['전기 사용 가능', '파쇄석', '그늘 많음', '프라이빗'],
    },
    {
        id: 'site-2',
        name: '영희네',
        type: 'AUTO',
        description: '계곡 물소리가 들리는 시원한 명당 자리입니다.',
        price: 40000,
        basePrice: 40000,
        maxOccupancy: 4,
        imageUrl: '/images/tent_view_wide_scenic.png',
        features: ['전기 사용 가능', '데크', '계곡 뷰', '편의시설 인접'],
    },
    {
        id: 'site-3',
        name: '민수네',
        type: 'AUTO',
        description: '모든 것이 준비된 럭셔리 글램핑 사이트입니다.',
        price: 130000,
        basePrice: 130000,
        maxOccupancy: 4,
        imageUrl: '/images/tent_view_hero.png',
        features: ['침대 구비', '개별 화장실', '에어컨', '냉장고'],
    },
    {
        id: 'site-4',
        name: '석이네',
        type: 'AUTO',
        description: '넓은 주차 공간과 함께하는 오토캠핑 사이트입니다.',
        price: 50000,
        basePrice: 50000,
        maxOccupancy: 6,
        imageUrl: '/images/tent_view_wide_scenic.png',
        features: ['차량 진입 가능', '파쇄석', '넓은 공간', '전기 사용 가능'],
    },
    {
        id: 'site-5',
        name: '순이네',
        type: 'AUTO',
        description: '아이들이 뛰어놀기 좋은 평지 사이트입니다.',
        price: 40000,
        basePrice: 40000,
        maxOccupancy: 4,
        imageUrl: '/images/tent_view_hero.png',
        features: ['잔디', '놀이터 인접', '전기 사용 가능'],
    },
    {
        id: 'site-6',
        name: '옥이네',
        type: 'AUTO',
        description: '나무 그늘이 풍부한 시원한 사이트입니다.',
        price: 40000,
        basePrice: 40000,
        maxOccupancy: 4,
        imageUrl: '/images/tent_view_wide_scenic.png',
        features: ['파쇄석', '그늘 많음', '해먹 설치 가능'],
    },
    {
        id: 'site-7',
        name: '담이네',
        type: 'AUTO',
        description: '카라반 진입이 가능한 넓은 사이트입니다.',
        price: 60000,
        basePrice: 60000,
        maxOccupancy: 6,
        imageUrl: '/images/tent_view_hero.png',
        features: ['카라반 가능', '전기 30A', '수도 시설'],
    },
    {
        id: 'site-8',
        name: '정이네',
        type: 'AUTO',
        description: '관리동과 가까워 편리한 사이트입니다.',
        price: 40000,
        basePrice: 40000,
        maxOccupancy: 4,
        imageUrl: '/images/tent_view_wide_scenic.png',
        features: ['편의시설 인접', '파쇄석', '와이파이'],
    },
];
