-- Create recommendation_pool table
create table if not exists recommendation_pool (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('cooking', 'play')),
  title text not null,
  description text,
  image_url text,
  tags jsonb default '{}'::jsonb, -- { "season": [], "weather": [], "composition": [], "difficulty": [] }
  content_url text,
  metadata jsonb default '{}'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Create nearby_events table
create table if not exists nearby_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  location text,
  latitude double precision,
  longitude double precision,
  start_date date,
  end_date date,
  image_url text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add beginner_chips to site_config if it doesn't exist
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'site_config' and column_name = 'beginner_chips') then
        alter table site_config add column beginner_chips jsonb default '[]'::jsonb;
    end if;
end $$;

-- Enable RLS
alter table recommendation_pool enable row level security;
alter table nearby_events enable row level security;

-- Policies for recommendation_pool
create policy "Public read recommendation_pool"
  on recommendation_pool for select
  using (true);

create policy "Admin all recommendation_pool"
  on recommendation_pool for all
  using (auth.uid() in (select id from admin_users));

-- Policies for nearby_events
create policy "Public read nearby_events"
  on nearby_events for select
  using (true);

create policy "Admin all nearby_events"
  on nearby_events for all
  using (auth.uid() in (select id from admin_users));

-- Insert sample data for chips if empty (Default 6 chips)
update site_config
set beginner_chips = '[
  {"label": "체크인", "icon": "Tent", "link": "/guide/checkin"},
  {"label": "매너타임", "icon": "Clock", "link": "/guide/manners"},
  {"label": "시설안내", "icon": "Map", "link": "/guide/facility"},
  {"label": "와이파이", "icon": "Wifi", "link": "/guide/wifi"},
  {"label": "주변마트", "icon": "ShoppingReel", "link": "/guide/mart"},
  {"label": "응급상황", "icon": "Siren", "link": "/guide/emergency"}
]'::jsonb
where id = 1 and (beginner_chips is null or jsonb_array_length(beginner_chips) = 0);
