-- 1. Create site_config table (if not exists)
create table if not exists site_config (
  id bigint primary key default 1 check (id = 1), -- Enforce singleton
  camp_name text not null default 'RAON.I',
  address_main text not null default '충청남도 예산군 응봉면 응봉서로 280',
  address_detail text default '지암리 277-1',
  phone_number text not null default '010-1234-5678',
  layout_image_url text,
  guide_map_url text,
  pricing_guide_text text,
  nearby_places jsonb default '[]'::jsonb,
  updated_at timestamptz default now()
);

-- Enable RLS for site_config
alter table site_config enable row level security;

-- Policies for site_config
drop policy if exists "Allow public read access" on site_config;
DROP POLICY IF EXISTS "Allow public read access" ON site_config;
create policy "Allow public read access" on site_config for select using (true);

drop policy if exists "Allow admin update access" on site_config;
DROP POLICY IF EXISTS "Allow admin update access" ON site_config;
create policy "Allow admin update access" on site_config for update using (auth.role() = 'authenticated');
)
on conflict (id) do nothing;


-- 2. Create recommendation_pool table
create table if not exists recommendation_pool (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('cooking', 'play')),
  title text not null,
  description text,
  image_url text,
  tags jsonb default '{}'::jsonb,
  content_url text,
  metadata jsonb default '{}'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Create nearby_events table
create table if not exists nearby_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  location text,
  latitude double precision,
  longitude double precision,
  start_date date,
  end_date date,
  image_url text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Add beginner_chips to site_config
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'site_config' and column_name = 'beginner_chips') then
        alter table site_config add column IF NOT EXISTS beginner_chips jsonb default '[]'::jsonb;
    end if;
end $$;

-- 5. Enable RLS for new tables
alter table recommendation_pool enable row level security;
alter table nearby_events enable row level security;

-- 6. Policies for recommendation_pool
drop policy if exists "Public read recommendation_pool" on recommendation_pool;
DROP POLICY IF EXISTS "Public read recommendation_pool" ON recommendation_pool;
create policy "Public read recommendation_pool" on recommendation_pool for select using (true);

drop policy if exists "Admin all recommendation_pool" on recommendation_pool;
DROP POLICY IF EXISTS "Admin all recommendation_pool" ON recommendation_pool;
create policy "Admin all recommendation_pool" on recommendation_pool for all using (auth.role() = 'authenticated');

-- 7. Policies for nearby_events
drop policy if exists "Public read nearby_events" on nearby_events;
DROP POLICY IF EXISTS "Public read nearby_events" ON nearby_events;
create policy "Public read nearby_events" on nearby_events for select using (true);

drop policy if exists "Admin all nearby_events" on nearby_events;
DROP POLICY IF EXISTS "Admin all nearby_events" ON nearby_events;
create policy "Admin all nearby_events" on nearby_events for all using (auth.role() = 'authenticated');

-- 8. Insert Default Beginner Chips
update site_config
set beginner_chips = '[
  {"label": "체크인", "icon": "Tent", "link": "/guide/checkin"},
  {"label": "매너타임", "icon": "Clock", "link": "/guide/manners"},
  {"label": "시설안내", "icon": "Map", "link": "/guide/facility"},
  {"label": "와이파이", "icon": "Wifi", "link": "/guide/wifi"},
  {"label": "주변마트", "icon": "ShoppingBag", "link": "/guide/mart"},
  {"label": "응급상황", "icon": "Siren", "link": "/guide/emergency"}
]'::jsonb
where id = 1 and (beginner_chips is null or jsonb_array_length(beginner_chips) = 0);
