-- 1. Create site_config table (if not exists)
create table if not exists site_config (
  id bigint primary key default 1 check (id = 1), -- Enforce singleton
  camp_name text not null default 'RAON.I',
  address_main text not null default '강원 춘천시 사북면 화악지암길 570',
  address_detail text default '지암리 277-1',
  phone_number text not null default '010-1234-5678',
  layout_image_url text,
  guide_map_url text,
  pricing_guide_text text,
  nearby_places jsonb default '[]'::jsonb,
  updated_at timestamptz default now()
);

-- Enable RLS for site_config
alter table site_config enable row level security;

-- Policies for site_config
drop policy if exists "Allow public read access" on site_config;
create policy "Allow public read access" on site_config for select using (true);

drop policy if exists "Allow admin update access" on site_config;
create policy "Allow admin update access" on site_config for update using (auth.role() = 'authenticated');

-- Insert Default Row for site_config
insert into site_config (id, camp_name, address_main, address_detail, phone_number, nearby_places)
values (
  1, 
  'RAON.I', 
  '강원 춘천시 사북면 화악지암길 570', 
  '지암리 277-1', 
  '010-1234-5678',
  '[
    {"title": "이상원 미술관", "desc": "차량 10분 거리 | 예술과 자연이 만나는 곳", "lat": 37.123, "lng": 127.123},
    {"title": "춘천 애니메이션 박물관", "desc": "차량 20분 거리 | 아이들과 함께하기 좋은 곳", "lat": 37.145, "lng": 127.155}
  ]'::jsonb
)
on conflict (id) do nothing;


-- 2. Create recommendation_pool table
create table if not exists recommendation_pool (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('cooking', 'play')),
  title text not null,
  description text,
  image_url text,
  tags jsonb default '{}'::jsonb,
  content_url text,
  metadata jsonb default '{}'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Create nearby_events table
create table if not exists nearby_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  location text,
  latitude double precision,
  longitude double precision,
  start_date date,
  end_date date,
  image_url text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Add beginner_chips to site_config
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'site_config' and column_name = 'beginner_chips') then
        alter table site_config add column beginner_chips jsonb default '[]'::jsonb;
    end if;
end $$;

-- 5. Enable RLS for new tables
alter table recommendation_pool enable row level security;
alter table nearby_events enable row level security;

-- 6. Policies for recommendation_pool
drop policy if exists "Public read recommendation_pool" on recommendation_pool;
create policy "Public read recommendation_pool" on recommendation_pool for select using (true);

drop policy if exists "Admin all recommendation_pool" on recommendation_pool;
create policy "Admin all recommendation_pool" on recommendation_pool for all using (auth.role() = 'authenticated');

-- 7. Policies for nearby_events
drop policy if exists "Public read nearby_events" on nearby_events;
create policy "Public read nearby_events" on nearby_events for select using (true);

drop policy if exists "Admin all nearby_events" on nearby_events;
create policy "Admin all nearby_events" on nearby_events for all using (auth.role() = 'authenticated');

-- 8. Insert Default Beginner Chips
update site_config
set beginner_chips = '[
  {"label": "체크인", "icon": "Tent", "link": "/guide/checkin"},
  {"label": "매너타임", "icon": "Clock", "link": "/guide/manners"},
  {"label": "시설안내", "icon": "Map", "link": "/guide/facility"},
  {"label": "와이파이", "icon": "Wifi", "link": "/guide/wifi"},
  {"label": "주변마트", "icon": "ShoppingBag", "link": "/guide/mart"},
  {"label": "응급상황", "icon": "Siren", "link": "/guide/emergency"}
]'::jsonb
where id = 1 and (beginner_chips is null or jsonb_array_length(beginner_chips) = 0);
